### ISSUE TITLE
Check NGE deployment on Titan

### ISSUE THREAD

**Issue by mturilli** [ATLAS-Titan/Harvester-NGE#13]

**Comment by mturilli** [comment]
Rutgers to provide REST endpoint to Danila

**Comment by DanilaOleynik** [comment]
Ping :-) It will be nice to start playing with NGE.

**Comment by andre-merzky** [comment]
I might be doing something really stupid - but does titan suddenly 'feature' an outbound firewall?

```
$ hostname -f
titan-ext1.ccs.ornl.gov

$ telnet one.radical-project.org 27017
Trying 144.76.72.175...
^C

$ ssh -v merzky@one.radical-project.org
OpenSSH_6.2p2, OpenSSL 0.9.8j-fips 07 Jan 2009
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 5: Applying options for *
debug1: Connecting to one.radical-project.org [144.76.72.175] port 22.
^C

```

Do you have any idea?  I'll open a support ticket.

**Comment by DanilaOleynik** [comment]
Looks a bit strange. SSH from Titan to CERN works ok. 

```
[Thu May 23 07:45:23 doleynik@titan-ext7] $ hostname 
titan-ext7
[Thu May 23 07:45:34 doleynik@titan-ext7] $ ssh lxplus.cern.ch
Warning: Permanently added the ECDSA host key for IP address '188.184.104.63' to the list of known hosts.
Password: 
Password: 
Last failed login: Thu May 23 13:46:56 CEST 2019 from 160.91.205.208 on ssh:notty
There was 1 failed login attempt since the last successful login.
* ********************************************************************
* Welcome to lxplus794.cern.ch, CentOS, 7.6.1810
* Archive of news is available in /etc/motd-archive
* Reminder: you have agreed to the CERN
*   computing rules, in particular OC5. CERN implements
*   the measures necessary to ensure compliance.
*   https://cern.ch/ComputingRules
* Puppet environment: qa, Roger state: production
* Foreman hostgroup: lxplus/nodes/login
* Availability zone: cern-geneva-a
* LXPLUS Public Login Service - https://cern.ch/lxplusdoc
* lxplus alias switch to CC7 on Apr 2nd 2019 . http://cern.ch/go/K7lq
* ********************************************************************
[Thu May 23 13:47:03 doleynik@lxplus794:~ ] $ 
```

```
[Thu May 23 07:44:37 doleynik@dtn35:~ ] $ hostname -f
dtn35.ccs.ornl.gov
[Thu May 23 07:50:26 doleynik@dtn35:~ ] $ ssh lxplus.cern.ch
Password: 
Last login: Sun May 19 22:00:40 2019 from 160.91.195.155
* ********************************************************************
* Welcome to lxplus720.cern.ch, CentOS, 7.6.1810
* Archive of news is available in /etc/motd-archive
* Reminder: you have agreed to the CERN
*   computing rules, in particular OC5. CERN implements
*   the measures necessary to ensure compliance.
*   https://cern.ch/ComputingRules
* Puppet environment: production, Roger state: production
* Foreman hostgroup: lxplus/nodes/login
* Availability zone: cern-geneva-c
* LXPLUS Public Login Service - https://cern.ch/lxplusdoc
* lxplus alias switch to CC7 on Apr 2nd 2019 . http://cern.ch/go/K7lq
* ********************************************************************
[Thu May 23 13:51:19 doleynik@lxplus720:~ ] $ 
```

There is some delay during establishing of connection,  but it works more or less ok.

**Comment by andre-merzky** [comment]
Thanks Danila - it seems our DB host got blacklisted - I opened a support ticket.

**Comment by andre-merzky** [comment]
Danila, 

we indeed got blacklisted (a rogue Jenkins script triggered that).  This is resolved now, and the  database connection is back up an running.  We now have an service endpoint running on `titan-ext1` on port `8090`.  You should be able to run something like [this python example](https://github.com/radical-cybertools/radical.nge/blob/master/examples/00_nge.py), the respective REST API calls should work as well of course (they are used under the hood in this example).

Some caveats:
  - I did not test the concurrent execution of multiple workloads, and am not sure that works reliably.  It might :-)  But be careful with the `restart` call then, as that will interrupt *all* running pilot jobs and workloads.
  - our ORTE installation on titan is broken again.  Given the limited amount of time left on titan, I am hesitant to invest time fixing it.  At the moment, the aprun backend is being used.

On the upside: we got some encouraging news on jsrun support on summit, and I am in the process of testing there.  If that turns out to resolve some of our problems there, I would suggest we switch to summit at the earliest possibility.  I'll create a service endpoint there as soon as the jsrun tests are done.

**Comment by DanilaOleynik** [comment]
Thanks Andre! 

I will start playing with code today. 
As only, I will be confident with the communication layer,  we will be rapidly migrating to Summit.

**Comment by DanilaOleynik** [comment]
Ok. Here are the first issues. 
May I ask for deployment of the NGE to the interactive DTN? ( dtn037 will be perfect). 
Looks like that NGE REST API accessible only from localhost. At the same time, Harvester is quite intensive with data transfers, and we got a requirement from OLCF to use DTNs.

I will play with titan-ext1 for the moment, but as only we will need to scale up so migration to DTN will be needed.


```
(nge) [Fri May 24 05:24:50 doleynik@titan-ext1] $ wget titan-ext1.ccs.ornl.gov:8090/
--2019-05-24 05:25:03--  http://titan-ext1.ccs.ornl.gov:8090/
Resolving titan-ext1.ccs.ornl.gov... 160.91.205.198
Connecting to titan-ext1.ccs.ornl.gov|160.91.205.198|:8090... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-24 05:25:03 ERROR 404: Not Found.

(nge) [Fri May 24 05:25:03 doleynik@titan-ext1] $ hostname -f 
titan-ext1.ccs.ornl.gov
```

```
(nge) [Fri May 24 05:17:54 doleynik@dtn37:~ ] $ hostname -f 
dtn37.ccs.ornl.gov
(nge) [Fri May 24 05:18:01 doleynik@dtn37:~ ] $ wget titan-ext1.ccs.ornl.gov:8090/
--2019-05-24 05:21:41--  http://titan-ext1.ccs.ornl.gov:8090/
Resolving titan-ext1.ccs.ornl.gov (titan-ext1.ccs.ornl.gov)... 160.91.205.198
Connecting to titan-ext1.ccs.ornl.gov (titan-ext1.ccs.ornl.gov)|160.91.205.198|:8090... failed: Connection refused.
```

**Comment by DanilaOleynik** [comment]
Hi, 

NGE still does not look healthy. I will be glad to start codding/debugging, but it's not possible without backend :-( I will need to give a status report about PanDA/NGE integration for ATLAS this Thursday, will be nice to have some positive news for this.

```
[Tue May 28 04:20:19 doleynik@titan-ext1] $ wget http://localhost:8090/
--2019-05-28 04:20:28--  http://localhost:8090/
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:24:11--  (try: 2)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:27:54--  (try: 3)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:31:38--  (try: 4)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:35:24--  (try: 5)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:39:11--  (try: 6)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:42:58--  (try: 7)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:46:47--  (try: 8)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:50:36--  (try: 9)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:54:26--  (try:10)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 04:58:18--  (try:11)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:02:09--  (try:12)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:06:01--  (try:13)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:09:52--  (try:14)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:13:44--  (try:15)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:17:35--  (try:16)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:21:26--  (try:17)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:25:18--  (try:18)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:29:09--  (try:19)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2019-05-28 05:33:01--  (try:20)  http://localhost:8090/
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.
```

**Comment by andre-merzky** [comment]
Hi Danila, 

a system change on Titan causes our bootstrapper to fail.  System changes are something we have to battle frequently :-(  I hope things stabilize once we move to Python3 over summer.  Either way, I'll fix this and will restart the service.

**Comment by andre-merzky** [comment]
Hi Danila, 

the endpoint should work again.  FWIW, the `wget` will still time out: there is no API call hooked behind the root url `/`.  You may want to use this instead:

```shell
$ curl -X PUT -H "Content-Type: application/json" -d '{"username":"guest","password":"guest"}' http://localhost:8090/login/
{"result": "guest", "success": true}
```

**Comment by DanilaOleynik** [comment]
Thanks Andre! 

Actually, wget shows is service alive or not, sometimes it's enough :-)  

```
wget http://localhost:8090/
--2019-05-29 02:28:15--  http://localhost:8090/
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:8090... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-29 02:28:15 ERROR 404: Not Found.

```
404 is good :-) in this case

**Comment by DanilaOleynik** [comment]
Looks like I did it again... NGE does not response for a few hours already. That happened after the first call of: "cancel_resources()" method. 
Good news, that I was able to play a bit with NGE and now a bit more familiar with the system. Will be nice to play a bit more, to formulate my questions more specific. 
Andre, may you have a look?

**Comment by andre-merzky** [comment]
indeed, you are right - it only survived 4 session.  I restarted it and will debug if that problem persists.

**Comment by andre-merzky** [comment]
It hangs again - SAGA seems to be unable to detect a killed pilot sometimes.  I'll restart and will start debugging the SAGA layer.

**Comment by DanilaOleynik** [comment]
Yep. Here is my test....

```
>>> import radical.nge as rn
>>> import radical.pilot as rp
>>> 
>>> nge = rn.NGE(binding=rn.RPS, url='http://localhost:8090/')
>>> nge.restart()
>>> nge.login(username='guest', password='guest')
u'guest'
>>> nge.uid
u'rp.session.titan-ext1.merzky1.018045.0003'
>>> psize = 1
>>> cores = 16
>>> nge.request_resources([{'resource': 'ornl.titan_aprun',
...                                       'queue': 'debug',
...                                       'project': 'CSC108',
...                                       'cores': psize + 15 * 1,  # add an agent node
...                                       'walltime': 60}])
>>> nge.wait_resource_states(states=rp.PMGR_ACTIVE)
```

Meanwhile, I saw that RP was running.

**Comment by andre-merzky** [comment]
Yes, I see pilots getting submitted.  The endpoint is up again, with some more logging enabled - lets see what that will yield...

**Comment by DanilaOleynik** [comment]
Looks like issue repeatable: pilots started, but NGE stuck on wait_resource_states(states=rp.PMGR_ACTIVE)

**Comment by DanilaOleynik** [comment]
Any updates?

**Comment by andre-merzky** [comment]
No, not yet unfortunately.  I apologize for the slow response times -- too many things to take care of in too little time...  *sigh*  Unfortunately its unlikely that my response times get much better - I'll do my best.

**Comment by andre-merzky** [comment]
I think I found the problem and pushed an update - an invalid logger call caused the pilot state monitor to fail, in a code path I recently enabled to get more debug information on NGE...  Duh!  It was triggered by your check on the pilot's `ACTIVE` state which I did not do in my tests.

Can you give it another try, please?

**Comment by DanilaOleynik** [comment]
Ok, I will need to keep pushing with requests, sorry.  
I tried one more time...  unfortunately, I broke server part again on the same call.   Should I upgrade nge libraries in my deployment before the next iteration?

**Comment by andre-merzky** [comment]
I did not want to discourage you pushing, at all - sorry if that came over the wrong way!  :-)

**Comment by andre-merzky** [comment]
Hi Danila, 

I think the  problems reflect that we (and Pavlo) used NGE as an experiment tool which only ran for the lifetime of one session per experiment, not as a persistent service endpoint.  I had to change the lifetime management for the sessions in NGE to better support the latter.  It includes the following changes:

  - a call to `login` will close any existing old session (incl. pilot termination)
  - a `logout` call has been added to close the session / terminate the pilots when wanted
  - the `close()` call is gone.

I think there is a problem left when tasks are submitted while a pilot is terminating - the scheduler  assigns them to that pilot before learning of its demise and NGE does not recover those units.  Please for now make sure that all pilots used by a session are still active when tasks are submitted. Submitting tasks before a pilot becomes active is unaffected, that still works.

The service should be up and running again.

**Comment by DanilaOleynik** [comment]
Hi Andre, 

In this case, we will need to have functionality, which will check that service is running. 
Harvester will interact with NGE from a few more or less independent threads. We will need to have a possibility, to check that NGE is running, before any interactions. In case NGE will be down, Harvester will try to launch it.    
I will continue exercises today.

**Comment by andre-merzky** [comment]
Hi Danila, 

I need to rephrase the above I think.

The assumption is that the NGE service is persistent - you will not need to start it, and will not need any indication of its lifeliness beyond the fact that you can connect it.

The service can concurrently host multiple user session, but is limited to one user per session.  A session is a set of requested resources (pilots) and tasks.  A session begins when a successful login is performed for that user, and ends when the user logs out.  When the user logs in twice, the session from the first login will be terminated (pilots get canceled), and a new (empty) session is created.

A session is identified by an encrypted cooked which contains the user ID and a session secret.


> Harvester will interact with NGE from a few more or less independent threads.

Yes,  because checking for resource state and submitting tasks is done in different harvester modules, right?  Will those modules be able to share the connection handle (and thus cookie)?  If not, then the current scheme should work.  If not, i.e. if each thread needs to connect to NGE on its own, then we would need a different session lifetime, and the ability to identify a session when connecting.  That can certainly be done,  and is not difficult to add - let me know!

Best, Andre.

**Comment by andre-merzky** [comment]
Danila, you seem to request a pilot which has 16 cores == 1 node.  Please request a pilot size of at least 2 nodes, as one node will currently be used for pilot management.  We can change that configuration if you want, but at the moment that is the default on Crays.

I'll open a ticket on why the NGE does not pick up the pilot failure.  I think this is why I still see other behavior than you...

**Comment by DanilaOleynik** [comment]
HI Andre, 

> The assumption is that the NGE service is persistent - you will not need to start it, and will not need any indication of its lifeliness beyond the fact that you can connect it.

Ok. 
> The service can concurrently host multiple user session, but is limited to one user per session. A session is a set of requested resources (pilots) and tasks. A session begins when a successful login is performed for that user, and ends when the user logs out. When the user logs in twice, the session from the first login will be terminated (pilots get canceled), and a new (empty) session is created.
> 
> A session is identified by an encrypted cooked which contains the user ID and a session secret. 
> 
It looks like, that Harvester in this case should connect with NGE once at startup.
> Harvester will interact with NGE from a few more or less independent threads.
> 
> Yes, because checking for resource state and submitting tasks is done in different harvester modules, right? Will those modules be able to share the connection handle (and thus cookie)?
> 
In general, i don’t think that there are architectural restrictions for this in Harvester, but….  all threads in Harvester is independent, so some machinery, which will check, that session already open is needed. (list sessions, list pilots etc.) 

> If not, then the current scheme should work. If not, i.e. if each thread needs to connect to NGE on its own, then we would need a different session lifetime, and the ability to identify a session when connecting. That can certainly be done, and is not difficult to add - let me know!
> 
Let’s keep it  as plan B. 


Cheers,
Danila

**Comment by DanilaOleynik** [comment]
Ops... I did it again. I had one open session, which was interrupted. I had start application again and call of nge.login(username='guest', password='guest') broke NGE on Titan  :-(...  
good news,  that I was able to launch a few RP and even got state 'DONE' for a set of tasks.

**Comment by DanilaOleynik** [comment]
Looks like that something happens with NGE on Titan again:

```
>>> nge.pilots_submit(sid, 
...                 [{ 'resource' : 'ornl.titan_aprun',
...                    'queue'    : 'debug',
...                    'project'  : 'CSC108',
...                    'cores'    : psize + 16 * 1,
...                    'walltime' : 60}])
---> PUT    http://guest:guest@localhost:8090/sessions/panda_worker_1/pilots/ [data:102]
     False  [IOError(116, 'Stale NFS file handle')]
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/lustre/atlas2/csc108/proj-shared/debug/nge/lib/python2.7/site-packages/radical/nge/nge_rs.py", line 175, in pilots_submit
    return self._query('put', '/sessions/%s/pilots/' % sid, descriptions)
  File "/lustre/atlas2/csc108/proj-shared/debug/nge/lib/python2.7/site-packages/radical/nge/nge_rs.py", line 100, in _query
    raise RuntimeError('query failed: %s' % result['error'])
RuntimeError: query failed: IOError(116, 'Stale NFS file handle')
>>> 
```

May you have a look?

**Comment by andre-merzky** [comment]
Given that Titan's batch system will be turned off in 5 days, do you mind if we switch to summit?

**Comment by DanilaOleynik** [comment]
Ok, let’s ,s try it. May I ask to send me the node name?
